apiVersion: v1
kind: Service

metadata:
  name: devops-demo
  namespace: demo
  annotations:
      cloud.google.com/load-balancer-type: Internal
      cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "devops-demo-neg-8080"}}}'

spec:
  type: LoadBalancer
  loadBalancerIP: "10.160.0.45"


  selector:
    app: devops-demo

  ports:

  - protocol: TCP
    port: 8080
    targetPort: 8080
